import { Car, FleetStats, Rental } from '../types';

export const MOCK_CARS: Car[] = [
  {
    id: 'car-1',
    name: 'Taycan Turbo S',
    brand: 'Porsche',
    model: 'Taycan',
    year: 2024,
    category: 'Electric',
    pricePerDay: 299,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 4,
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=800',
    rating: 4.9,
    tripsCount: 42,
    location: 'Downtown Hub - Terminal 1',
    features: ['Autopilot', 'Fast Charging', 'Panaromic Roof', 'Bose Audio'],
  },
  {
    id: 'car-2',
    name: 'RS e-tron GT',
    brand: 'Audi',
    model: 'e-tron',
    year: 2024,
    category: 'Sports',
    pricePerDay: 249,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 5,
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?q=80&w=800',
    rating: 4.8,
    tripsCount: 28,
    location: 'Airport Express Center',
    features: ['Quattro AWD', 'Matrix LED', 'Head-Up Display'],
  },
  {
    id: 'car-3',
    name: 'Model S Plaid',
    brand: 'Tesla',
    model: 'Model S',
    year: 2023,
    category: 'Electric',
    pricePerDay: 219,
    fuelType: 'Electric',
    transmission: 'Automatic',
    seats: 5,
    status: 'Rented',
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=800',
    rating: 4.95,
    tripsCount: 89,
    location: 'Westside Station',
    features: ['Full Self-Driving', 'Yoke Steering', 'Ludicrous Mode'],
  },
  {
    id: 'car-4',
    name: 'G 63 AMG',
    brand: 'Mercedes-Benz',
    model: 'G-Class',
    year: 2024,
    category: 'SUV',
    pricePerDay: 399,
    fuelType: 'Petrol',
    transmission: 'Automatic',
    seats: 5,
    status: 'Available',
    imageUrl: 'https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?q=80&w=800',
    rating: 4.92,
    tripsCount: 15,
    location: 'Luxury Fleet Lounge',
    features: ['V8 Biturbo', 'Burmester Sound', 'Offroad Package'],
  },
];

export const MOCK_FLEET_STATS: FleetStats = {
  totalVehicles: 48,
  activeRentals: 32,
  availableVehicles: 12,
  maintenanceVehicles: 4,
  totalRevenue: 128450,
  utilizationRate: 78.5,
};

export const MOCK_RENTALS: Rental[] = [
  {
    id: 'rent-101',
    carId: 'car-1',
    carName: 'Porsche Taycan Turbo S',
    startDate: '2026-09-10',
    endDate: '2026-09-14',
    totalPrice: 1196,
    status: 'Upcoming',
    pickupLocation: 'Downtown Hub - Terminal 1',
    dropoffLocation: 'Downtown Hub - Terminal 1',
  },
];
