import { Vehicle } from '../types';

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: 'veh-corolla-01',
    brand: 'Toyota',
    model: 'Corolla Hybrid',
    year: 2024,
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1623869675781-80aa31012a5a?q=80&w=800',
    pricePerDay: 55,
    rating: 4.88,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    location: 'Airport Terminal 1 - Hub West',
    availability: 'Available',
    features: [
      'Toyota Safety Sense 3.0',
      'Apple CarPlay & Android Auto',
      'Adaptive Cruise Control',
      'Lane Tracing Assist',
      'Smart Key System',
      'Dual-Zone Automatic Climate Control',
    ],
    description:
      'The 2024 Toyota Corolla Hybrid combines legendary durability with state-of-the-art hybrid efficiency. Delivering up to 50 MPG with whisper-quiet city operation, smooth electronic continuously variable transmission, and generous rear passenger legroom.',
  },
  {
    id: 'veh-civic-02',
    brand: 'Honda',
    model: 'Civic Touring',
    year: 2024,
    category: 'Sedan',
    image: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?q=80&w=800',
    pricePerDay: 62,
    rating: 4.91,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Petrol',
    location: 'Downtown Tech District Hub',
    availability: 'Available',
    features: [
      'Bose 12-Speaker Premium Sound',
      'Honda Sensing Suite',
      'Wireless Phone Charger',
      'Blind Spot Information System',
      'Power Sunroof',
      '10.2-inch Digital Instrument Cluster',
    ],
    description:
      'A refined dynamic driver sedan equipped with a turbocharged 1.5L engine. Boasting an ultra-clean acoustic cabin, sculpted leather-trimmed seating, and responsive handling suited for both metropolitan sprints and scenic coastal drives.',
  },
  {
    id: 'veh-yaris-03',
    brand: 'Toyota',
    model: 'Yaris Cross',
    year: 2023,
    category: 'Economy',
    image: 'https://images.unsplash.com/photo-1590362891991-f776e747a588?q=80&w=800',
    pricePerDay: 42,
    rating: 4.76,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Petrol',
    location: 'Central Metro Station Station Bay 4',
    availability: 'Available',
    features: [
      'Compact Parking Assist',
      'Touchscreen Infotainment',
      'Rearview Camera',
      'Eco Drive Monitor',
      'Automatic Emergency Braking',
      'USB-C Fast Charging',
    ],
    description:
      'The Toyota Yaris is the definitive city explorer. Agile, ultra-efficient, and effortless to park in snug metropolitan spaces while retaining surprisingly spacious interior cargo utility and contemporary connectivity.',
  },
  {
    id: 'veh-tucson-04',
    brand: 'Hyundai',
    model: 'Tucson N Line',
    year: 2024,
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=800',
    pricePerDay: 85,
    rating: 4.84,
    seats: 5,
    doors: 5,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    location: 'Airport North Logistics Pavilion',
    availability: 'Available',
    features: [
      'HTRAC All-Wheel Drive',
      'Panoramic Curved Display',
      'Surround View 360 Camera',
      'Smart Power Liftgate',
      'Heated & Ventilated Front Seats',
      'Highway Driving Assist',
    ],
    description:
      'Sculpted with striking parametric jewel surfaces, the Hyundai Tucson delivers generous SUV capacity with high-efficiency hybrid power. Features plush sport seating, comprehensive active driver assistance, and an expansive panoramic roof.',
  },
  {
    id: 'veh-sportage-05',
    brand: 'Kia',
    model: 'Sportage X-Line',
    year: 2024,
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?q=80&w=800',
    pricePerDay: 89,
    rating: 4.82,
    seats: 5,
    doors: 5,
    transmission: 'Automatic',
    fuel: 'Diesel',
    location: 'Suburban Transit Plaza - Level 2',
    availability: 'Available',
    features: [
      'Dual 12.3-inch Panoramic Screens',
      'All-Terrain Drive Modes',
      'Harman Kardon Audio',
      'Smart Cruise Control with Stop & Go',
      'Roof Rack Utility Rails',
      'Remote Smart Parking Assist',
    ],
    description:
      'The Kia Sportage X-Line stands out with high-clearance rugged capability and dramatic LED styling. Offering exceptional fuel range on highway routes, a cavernous rear cargo bay, and intuitive digital cockpit integration.',
  },
  {
    id: 'veh-fortuner-06',
    brand: 'Toyota',
    model: 'Fortuner GR Sport',
    year: 2024,
    category: 'SUV',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=800',
    pricePerDay: 125,
    rating: 4.93,
    seats: 7,
    doors: 5,
    transmission: 'Automatic',
    fuel: 'Diesel',
    location: 'Grand Plaza Fleet Depot',
    availability: 'Available',
    features: [
      'Heavy-Duty 4x4 with Differential Lock',
      'Full 7-Passenger Leather Seating',
      'Monotube Performance Shock Absorbers',
      'JBL 9-Speaker Cinematic System',
      'Panoramic View Monitor',
      'Rear Air Conditioning Controls',
    ],
    description:
      'Engineered on a robust ladder-frame chassis, the Toyota Fortuner GR Sport combines uncompromising 7-passenger capacity with extreme durability. Perfect for extended family road trips, mountain expeditions, and VIP transport.',
  },
  {
    id: 'veh-eclass-07',
    brand: 'Mercedes-Benz',
    model: 'E 350 4MATIC',
    year: 2024,
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=800',
    pricePerDay: 195,
    rating: 4.97,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Petrol',
    location: 'Executive VIP Terminal & Lounge',
    availability: 'Available',
    features: [
      'MBUX Superscreen Digital Display',
      'Burmester 4D Surround Sound',
      'Active Ambient Lighting',
      'AIRMATIC Air Suspension',
      'Acoustic Comfort Acoustic Glass',
      'Heated Armrests & Steering Wheel',
    ],
    description:
      'The pinnacle of business-class luxury mobility. The Mercedes-Benz E-Class redefines serene grand touring with active road-noise cancellation, hand-crafted Nappa leather appointments, and effortless turbocharged 4MATIC power delivery.',
  },
  {
    id: 'veh-bmw5-08',
    brand: 'BMW',
    model: '530e M Sport',
    year: 2024,
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800',
    pricePerDay: 185,
    rating: 4.94,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Hybrid',
    location: 'Financial Center Tower Hub',
    availability: 'Available',
    features: [
      'BMW Curved Display with iDrive 8.5',
      'M Sport Aerodynamics Package',
      'Interaction Bar with Ambient Facets',
      'Driving Assistant Professional',
      'Wireless Apple CarPlay / Android Auto',
      'Panoramic Glass Skyroof',
    ],
    description:
      'The BMW 530e M Sport seamlessly integrates plug-in electric propulsion with sports saloon pedigree. Delivers instant electric torque for quiet city commuting, coupled with an eager TwinPower Turbo powerplant for unrestricted range.',
  },
  {
    id: 'veh-elantra-09',
    brand: 'Hyundai',
    model: 'Elantra Preferred',
    year: 2023,
    category: 'Economy',
    image: 'https://images.unsplash.com/photo-1542282088-72c9c27ed0cd?q=80&w=800',
    pricePerDay: 46,
    rating: 4.79,
    seats: 5,
    doors: 4,
    transmission: 'Automatic',
    fuel: 'Petrol',
    location: 'Westside Station Hub',
    availability: 'Available',
    features: [
      'SmartSense Safety Suite',
      'Dual 10.25-inch Screens',
      'Heated Front Seats',
      'Hands-Free Smart Trunk',
      'Bluetooth Multi-Pairing',
      'LED Daytime Running Lights',
    ],
    description:
      'Dynamic origami-like exterior styling packed with premium features at accessible pricing. The Hyundai Elantra provides standout road presence, best-in-class rear legroom, and refined highway cruising confidence.',
  },
  {
    id: 'veh-q7-10',
    brand: 'Audi',
    model: 'Q7 Prestige',
    year: 2024,
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800',
    pricePerDay: 175,
    rating: 4.92,
    seats: 7,
    doors: 5,
    transmission: 'Automatic',
    fuel: 'Petrol',
    location: 'Luxury Fleet Lounge - Bay 12',
    availability: 'Rented',
    features: [
      'Quattro Permanent All-Wheel Drive',
      'Bang & Olufsen 3D Advanced Sound',
      'Matrix-design LED Headlights with Laser Light',
      'Valcona/Cricket Leather Upholstery',
      'Adaptive Air Suspension',
      'Power Folding Third Row',
    ],
    description:
      'The Audi Q7 Prestige brings understated elegance to luxury 7-passenger utility. With Quattro all-wheel drive stability, ultra-quiet cabin acoustics, and three rows of versatile seating, every journey feels first-class.',
  },
];
